version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
install:
- if not exist gtk-sharp-2.12.25.msi appveyor DownloadFile http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.25.msi
- msiexec /i gtk-sharp-2.12.25.msi /qn /norestart
- git submodule update --init --recursive
build:
  project: ZoraGenGtk.sln
  verbosity: minimal
after_build:
- 7z a ZoraGenGtk.zip %APPVEYOR_BUILD_FOLDER%\ZoraGenGtk\bin\%CONFIGURATION%\ZoraGenGtk.exe %APPVEYOR_BUILD_FOLDER%\ZoraGenGtk\bin\%CONFIGURATION%\ZoraSharp.dll
test: off
artifacts:
- path: ZoraGenGtk.zip
  name: ZoraGenGtk
